//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFEnhance.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFEnhance.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} 接受来自 {0} 的好友请求.
        /// </summary>
        internal static string AcceptFriendRequest {
            get {
                return ResourceManager.GetString("AcceptFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubID | 名称 (仅显示免费Sub).
        /// </summary>
        internal static string AccountFreeSubTitle {
            get {
                return ResourceManager.GetString("AccountFreeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到账户中的免费 Demo Sub.
        /// </summary>
        internal static string AccountSubDemoSubNotFount {
            get {
                return ResourceManager.GetString("AccountSubDemoSubNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 免费赠送.
        /// </summary>
        internal static string AccountSubFree {
            get {
                return ResourceManager.GetString("AccountSubFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 礼物/玩家通行证.
        /// </summary>
        internal static string AccountSubGift {
            get {
                return ResourceManager.GetString("AccountSubGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的参数.
        /// </summary>
        internal static string AccountSubInvalidArg {
            get {
                return ResourceManager.GetString("AccountSubInvalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1}.
        /// </summary>
        internal static string AccountSubItem {
            get {
                return ResourceManager.GetString("AccountSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未拥有该Sub.
        /// </summary>
        internal static string AccountSubNotOwn {
            get {
                return ResourceManager.GetString("AccountSubNotOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除了 {0} 个 Demo.
        /// </summary>
        internal static string AccountSubRemovedDemos {
            get {
                return ResourceManager.GetString("AccountSubRemovedDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除 {0} {1}.
        /// </summary>
        internal static string AccountSubRemovedItem {
            get {
                return ResourceManager.GetString("AccountSubRemovedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 零售.
        /// </summary>
        internal static string AccountSubRetail {
            get {
                return ResourceManager.GetString("AccountSubRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam 商店.
        /// </summary>
        internal static string AccountSubStore {
            get {
                return ResourceManager.GetString("AccountSubStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型 | 名称.
        /// </summary>
        internal static string AccountSubTitle {
            get {
                return ResourceManager.GetString("AccountSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string AccountSubUnknown {
            get {
                return ResourceManager.GetString("AccountSubUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前已经是最新版本, 无需更新插件.
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 标签: {0}.
        /// </summary>
        internal static string AppCategories {
            get {
                return ResourceManager.GetString("AppCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发售.
        /// </summary>
        internal static string AppComingSoon {
            get {
                return ResourceManager.GetString("AppComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可购买.
        /// </summary>
        internal static string AppDelisted {
            get {
                return ResourceManager.GetString("AppDelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 名称: {0}.
        /// </summary>
        internal static string AppDetailName {
            get {
                return ResourceManager.GetString("AppDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1}.
        /// </summary>
        internal static string AppDetailResult {
            get {
                return ResourceManager.GetString("AppDetailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 开发商: {0}.
        /// </summary>
        internal static string AppDevelopers {
            get {
                return ResourceManager.GetString("AppDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 折扣: -{0}% {1}.
        /// </summary>
        internal static string AppDiscount {
            get {
                return ResourceManager.GetString("AppDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - DLC: {0}.
        /// </summary>
        internal static string AppDlcInfo {
            get {
                return ResourceManager.GetString("AppDlcInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 游戏本体: {0} {1}.
        /// </summary>
        internal static string AppFullGame {
            get {
                return ResourceManager.GetString("AppFullGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 分类: {0}.
        /// </summary>
        internal static string AppGenres {
            get {
                return ResourceManager.GetString("AppGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已申请.
        /// </summary>
        internal static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Metacritic 评分: {0}.
        /// </summary>
        internal static string AppMetacriticScore {
            get {
                return ResourceManager.GetString("AppMetacriticScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 折扣: 未打折.
        /// </summary>
        internal static string AppNoDiscount {
            get {
                return ResourceManager.GetString("AppNoDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 发型商: {0}.
        /// </summary>
        internal static string AppPublishers {
            get {
                return ResourceManager.GetString("AppPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 发售日期: {0}.
        /// </summary>
        internal static string AppReleasedDate {
            get {
                return ResourceManager.GetString("AppReleasedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -  [{0}].
        /// </summary>
        internal static string AppReleasedDateEx {
            get {
                return ResourceManager.GetString("AppReleasedDateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 简介: {0}.
        /// </summary>
        internal static string AppShortDescription {
            get {
                return ResourceManager.GetString("AppShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Steam 评价数量: {0}.
        /// </summary>
        internal static string AppSteamRecommended {
            get {
                return ResourceManager.GetString("AppSteamRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Sub/{0} {1}.
        /// </summary>
        internal static string AppSubInfo {
            get {
                return ResourceManager.GetString("AppSubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 支持平台: Win{0} Mac{1} Linux{2}.
        /// </summary>
        internal static string AppSupportedPlatforms {
            get {
                return ResourceManager.GetString("AppSupportedPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 类型: {0}.
        /// </summary>
        internal static string AppType {
            get {
                return ResourceManager.GetString("AppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLC.
        /// </summary>
        internal static string AppTypeDLC {
            get {
                return ResourceManager.GetString("AppTypeDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏 / 软件.
        /// </summary>
        internal static string AppTypeGame {
            get {
                return ResourceManager.GetString("AppTypeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐.
        /// </summary>
        internal static string AppTypeMusic {
            get {
                return ResourceManager.GetString("AppTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} | {1}.
        /// </summary>
        internal static string AreaItem {
            get {
                return ResourceManager.GetString("AreaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} | {1} | *.
        /// </summary>
        internal static string AreaItemCurrent {
            get {
                return ResourceManager.GetString("AreaItemCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数为空.
        /// </summary>
        internal static string ArgsIsEmpty {
            get {
                return ResourceManager.GetString("ArgsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数错误, {0} 必须为整数.
        /// </summary>
        internal static string ArgumentNotInteger {
            get {
                return ResourceManager.GetString("ArgumentNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASFEnhanceDevFuture配置项已经过时, 请根据文档修改.
        /// </summary>
        internal static string ASFEConfigWarning {
            get {
                return ResourceManager.GetString("ASFEConfigWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本: {0}.
        /// </summary>
        internal static string ASFECurrentVersion {
            get {
                return ResourceManager.GetString("ASFECurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASFEnhance&apos;s Curator.
        /// </summary>
        internal static string ASFEnhanceCurator {
            get {
                return ResourceManager.GetString("ASFEnhanceCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASFEnhance&apos;s Group.
        /// </summary>
        internal static string ASFEnhanceGroup {
            get {
                return ResourceManager.GetString("ASFEnhanceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线版本: {0}.
        /// </summary>
        internal static string ASFEOnlineVersion {
            get {
                return ResourceManager.GetString("ASFEOnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 插件版本: {0}.
        /// </summary>
        internal static string ASFEPluginVersion {
            get {
                return ResourceManager.GetString("ASFEPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用命令 ASFEUPDATE / AU 自动更新插件.
        /// </summary>
        internal static string ASFEUpdateTips {
            get {
                return ResourceManager.GetString("ASFEUpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用命令 ASFEVERSION / AV 检查插件更新.
        /// </summary>
        internal static string ASFEVersionTips {
            get {
                return ResourceManager.GetString("ASFEVersionTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 附件: .
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码 | 区域名称 | 当前区域.
        /// </summary>
        internal static string AvailableAreaHeader {
            get {
                return ResourceManager.GetString("AvailableAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 响应为空.
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 类型无效 [SUB|BUNDLE].
        /// </summary>
        internal static string CartInvalidType {
            get {
                return ResourceManager.GetString("CartInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购物车是空的.
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} {1} {2:F2}.
        /// </summary>
        internal static string CartItemInfo {
            get {
                return ResourceManager.GetString("CartItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作为礼物购买: {0}.
        /// </summary>
        internal static string CartPurchaseGift {
            get {
                return ResourceManager.GetString("CartPurchaseGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为自己购买: {0}.
        /// </summary>
        internal static string CartPurchaseSelf {
            get {
                return ResourceManager.GetString("CartPurchaseSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空购物车: {0}.
        /// </summary>
        internal static string CartResetResult {
            get {
                return ResourceManager.GetString("CartResetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购物车总额: {0:F2} {1}.
        /// </summary>
        internal static string CartTotalPrice {
            get {
                return ResourceManager.GetString("CartTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | 参数错误.
        /// </summary>
        internal static string CheckGameItemError {
            get {
                return ResourceManager.GetString("CheckGameItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1}.
        /// </summary>
        internal static string CheckGameItemFailed {
            get {
                return ResourceManager.GetString("CheckGameItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1} | {2} | {3} | {4}.
        /// </summary>
        internal static string CheckGameItemSuccess {
            get {
                return ResourceManager.GetString("CheckGameItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID | 游戏名 | 已拥有 | 愿望单 | 关注.
        /// </summary>
        internal static string CheckGameListTitle {
            get {
                return ResourceManager.GetString("CheckGameListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧的插件备份已经自动清理.
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧的插件备份清理失败.
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam商店的Cookies:.
        /// </summary>
        internal static string ClientCookies {
            get {
                return ResourceManager.GetString("ClientCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令帮助:.
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到相关命令的帮助.
        /// </summary>
        internal static string CommandHelpCmdNotFound {
            get {
                return ResourceManager.GetString("CommandHelpCmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} {1} : {2}.
        /// </summary>
        internal static string CommandHelpNoShortName {
            get {
                return ResourceManager.GetString("CommandHelpNoShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无描述.
        /// </summary>
        internal static string CommandHelpNoUsage {
            get {
                return ResourceManager.GetString("CommandHelpNoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * 可用缩写 : {0}.
        /// </summary>
        internal static string CommandHelpWithShortName {
            get {
                return ResourceManager.GetString("CommandHelpWithShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1}.
        /// </summary>
        internal static string CookieItem {
            get {
                return ResourceManager.GetString("CookieItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClanID | 鉴赏家名称 | 关注人数.
        /// </summary>
        internal static string CuratorListTitle {
            get {
                return ResourceManager.GetString("CuratorListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-Hans.
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 是 NULL.
        /// </summary>
        internal static string DataIsNull {
            get {
                return ResourceManager.GetString("DataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除 {0} 的评测: .
        /// </summary>
        internal static string DeleteReview {
            get {
                return ResourceManager.GetString("DeleteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 描述: {0}.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASFEhance 开发者特性已开启.
        /// </summary>
        internal static string DevFeatureEnabledWarning {
            get {
                return ResourceManager.GetString("DevFeatureEnabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未启用 ASFEnhance.DevFeature , 该命令不可用.
        /// </summary>
        internal static string DevFeatureNotEnabled {
            get {
                return ResourceManager.GetString("DevFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载插件失败!.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用邮件通知.
        /// </summary>
        internal static string EnableEmailNotification {
            get {
                return ResourceManager.GetString("EnableEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Access: {0}.
        /// </summary>
        internal static string ErrorLogAccess {
            get {
                return ResourceManager.GetString("ErrorLogAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - ASF 版本: {0}.
        /// </summary>
        internal static string ErrorLogASFVersion {
            get {
                return ResourceManager.GetString("ErrorLogASFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 错误消息: {0}.
        /// </summary>
        internal static string ErrorLogErrorMessage {
            get {
                return ResourceManager.GetString("ErrorLogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 错误类型: {0}.
        /// </summary>
        internal static string ErrorLogErrorName {
            get {
                return ResourceManager.GetString("ErrorLogErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 原始消息: {0}.
        /// </summary>
        internal static string ErrorLogOriginMessage {
            get {
                return ResourceManager.GetString("ErrorLogOriginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 插件版本: {0}.
        /// </summary>
        internal static string ErrorLogPluginVersion {
            get {
                return ResourceManager.GetString("ErrorLogPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASFenhance 遇到错误, 日志如下.
        /// </summary>
        internal static string ErrorLogTitle {
            get {
                return ResourceManager.GetString("ErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未同意 ASFEnhance.EULA , 该命令不可用.
        /// </summary>
        internal static string EulaCmdUnavilable {
            get {
                return ResourceManager.GetString("EulaCmdUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未同意 ASFEnhance.EULA , 无法使用IPC功能.
        /// </summary>
        internal static string EulaFeatureUnavilable {
            get {
                return ResourceManager.GetString("EulaFeatureUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未同意 EULA , 部分命令已禁用.
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 领取每日贴纸: {0}.
        /// </summary>
        internal static string EventClaimItem {
            get {
                return ResourceManager.GetString("EventClaimItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每日探索队列: {0}.
        /// </summary>
        internal static string EventQueue {
            get {
                return ResourceManager.GetString("EventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取投票信息失败.
        /// </summary>
        internal static string EventReadBadgeStatusFailed {
            get {
                return ResourceManager.GetString("EventReadBadgeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节日活动已完成.
        /// </summary>
        internal static string EventTaskComplete {
            get {
                return ResourceManager.GetString("EventTaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Award 投票: {0} / {1}.
        /// </summary>
        internal static string EventVoteResponse {
            get {
                return ResourceManager.GetString("EventVoteResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 探索队列任务将尽快触发.
        /// </summary>
        internal static string ExplorerStart {
            get {
                return ResourceManager.GetString("ExplorerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取App信息失败, 可能AppID错误, 或者锁区.
        /// </summary>
        internal static string FetchAppDetailFailed {
            get {
                return ResourceManager.GetString("FetchAppDetailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取 {0} 失败.
        /// </summary>
        internal static string FetchDataFailed {
            get {
                return ResourceManager.GetString("FetchDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是有效的AvatarId.
        /// </summary>
        internal static string GameAvatarInvalidAvatarId {
            get {
                return ResourceManager.GetString("GameAvatarInvalidAvatarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是有效的AppId.
        /// </summary>
        internal static string GameAvatarInvalidGameId {
            get {
                return ResourceManager.GetString("GameAvatarInvalidGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 类型无效 [APP|SUB|BUNDLE].
        /// </summary>
        internal static string GameInvalidType {
            get {
                return ResourceManager.GetString("GameInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取在线汇率失败.
        /// </summary>
        internal static string GetExchangeRateFailed {
            get {
                return ResourceManager.GetString("GetExchangeRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取个人资料失败.
        /// </summary>
        internal static string GetProfileFailed {
            get {
                return ResourceManager.GetString("GetProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取插件发行版信息失败!.
        /// </summary>
        internal static string GetReleaseInfoFailed {
            get {
                return ResourceManager.GetString("GetReleaseInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取商店名称出错.
        /// </summary>
        internal static string GetStoreNameFailed {
            get {
                return ResourceManager.GetString("GetStoreNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 由 {0} 发送.
        /// </summary>
        internal static string GifteeName {
            get {
                return ResourceManager.GetString("GifteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 版本 {1}.
        /// </summary>
        internal static string GiftMessage {
            get {
                return ResourceManager.GetString("GiftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 由 {0} 发送.
        /// </summary>
        internal static string GiftSignature {
            get {
                return ResourceManager.GetString("GiftSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未加入任何群组.
        /// </summary>
        internal static string GroupListEmpty {
            get {
                return ResourceManager.GetString("GroupListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1} | {2}.
        /// </summary>
        internal static string GroupListItem {
            get {
                return ResourceManager.GetString("GroupListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No | 群组名称 | 群组ID.
        /// </summary>
        internal static string GroupListTitle {
            get {
                return ResourceManager.GetString("GroupListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ ]: 可选参数, &lt; &gt;: 数组(使用,分隔).
        /// </summary>
        internal static string HelpArgsExplain {
            get {
                return ResourceManager.GetString("HelpArgsExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已加入.
        /// </summary>
        internal static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入群组 {0}: {1}.
        /// </summary>
        internal static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到结果.
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schinese.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出群组: {0}.
        /// </summary>
        internal static string LeaveGroup {
            get {
                return ResourceManager.GetString("LeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多行结果:.
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络错误.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无参数.
        /// </summary>
        internal static string NoArgs {
            get {
                return ResourceManager.GetString("NoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无可用区域选项, 结算货币为钱包货币.
        /// </summary>
        internal static string NoAvailableArea {
            get {
                return ResourceManager.GetString("NoAvailableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未关注任何鉴赏家.
        /// </summary>
        internal static string NotFollowAnyCurator {
            get {
                return ResourceManager.GetString("NotFollowAnyCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML解析失败!.
        /// </summary>
        internal static string ParseHtmlFailed {
            get {
                return ResourceManager.GetString("ParseHtmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者 Chr_, 联系方式 chr@chrxw.com.
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱发电: https://afdian.net/@chr233.
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 版本 {1}.
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 徽章: {0}.
        /// </summary>
        internal static string ProfileBadges {
            get {
                return ResourceManager.GetString("ProfileBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好友: {0} / {1}.
        /// </summary>
        internal static string ProfileFriends {
            get {
                return ResourceManager.GetString("ProfileFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏: {0}.
        /// </summary>
        internal static string ProfileGames {
            get {
                return ResourceManager.GetString("ProfileGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组: {0}.
        /// </summary>
        internal static string ProfileGroups {
            get {
                return ResourceManager.GetString("ProfileGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指南: {0}.
        /// </summary>
        internal static string ProfileGuide {
            get {
                return ResourceManager.GetString("ProfileGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人资料:.
        /// </summary>
        internal static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艺术作品: {0}.
        /// </summary>
        internal static string ProfileImages {
            get {
                return ResourceManager.GetString("ProfileImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级: {0}.
        /// </summary>
        internal static string ProfileLevel {
            get {
                return ResourceManager.GetString("ProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称: {0}.
        /// </summary>
        internal static string ProfileNickname {
            get {
                return ResourceManager.GetString("ProfileNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评测: {0}.
        /// </summary>
        internal static string ProfileRecommended {
            get {
                return ResourceManager.GetString("ProfileRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截图: {0}.
        /// </summary>
        internal static string ProfileScreenshots {
            get {
                return ResourceManager.GetString("ProfileScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态: {0}.
        /// </summary>
        internal static string ProfileState {
            get {
                return ResourceManager.GetString("ProfileState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频: {0}.
        /// </summary>
        internal static string ProfileVideos {
            get {
                return ResourceManager.GetString("ProfileVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创意工坊: {0}.
        /// </summary>
        internal static string ProfileWorkshop {
            get {
                return ResourceManager.GetString("ProfileWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 基准汇率 {0}.
        /// </summary>
        internal static string PruchaseHistoryAboutBaseRate {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 计算结果由 {0} 生成, 仅供参考.
        /// </summary>
        internal static string PruchaseHistoryAboutPlugin {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 在线汇率数据来自 ExchangeRate-API.com.
        /// </summary>
        internal static string PruchaseHistoryAboutRateSource {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutRateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 汇率数据更新时间: {0:g}.
        /// </summary>
        internal static string PruchaseHistoryAboutUpdateTime {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 额度*1.8 - 送礼: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryCreditMax {
            get {
                return ResourceManager.GetString("PruchaseHistoryCreditMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 额度*1.0 - 送礼: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryCreditMin {
            get {
                return ResourceManager.GetString("PruchaseHistoryCreditMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 外部*1.8 - 送礼: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryExternalMax {
            get {
                return ResourceManager.GetString("PruchaseHistoryExternalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 外部*1.0 - 送礼: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryExternalMin {
            get {
                return ResourceManager.GetString("PruchaseHistoryExternalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据说明:.
        /// </summary>
        internal static string PruchaseHistoryGroupAbout {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 额度推算(仅供参考):.
        /// </summary>
        internal static string PruchaseHistoryGroupGiftCredit {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupGiftCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  2.其他类型的消费:.
        /// </summary>
        internal static string PruchaseHistoryGroupOther {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据统计(仅供参考):.
        /// </summary>
        internal static string PruchaseHistoryGroupStatus {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  1.按购买类型分类(不含已退款的消费):.
        /// </summary>
        internal static string PruchaseHistoryGroupType {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 外部消费总和: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryStatusTotalExternalPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryStatusTotalExternalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 礼物赠送总和: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryStatusTotalGift {
            get {
                return ResourceManager.GetString("PruchaseHistoryStatusTotalGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 有效额度总和: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryStatusTotalPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryStatusTotalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - 外部: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeExternal {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 礼物赠送: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeGiftPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeGiftPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 游戏内购: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeInGamePurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeInGamePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 市场购买: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeMarketPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeMarketPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 市场出售: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeMarketSelling {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeMarketSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 其他类型: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeOther {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 退款: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeRefunded {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 商店购买: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeStorePurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeStorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - 余额: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeWallet {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 余额充值: {0:0.00} {1}.
        /// </summary>
        internal static string PruchaseHistoryTypeWalletPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeWalletPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购物车是空的,无需结账.
        /// </summary>
        internal static string PurchaseCartFailureEmpty {
            get {
                return ResourceManager.GetString("PurchaseCartFailureEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买失败, FinalizeTransaction 返回值为空.
        /// </summary>
        internal static string PurchaseCartFailureFinalizeTransactionIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartFailureFinalizeTransactionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买失败, GetFinalPrice 返回值为空.
        /// </summary>
        internal static string PurchaseCartGetFinalPriceIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartGetFinalPriceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买失败, transID 为Null.
        /// </summary>
        internal static string PurchaseCartTransIDIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartTransIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买完成, 消费金额: {0}.
        /// </summary>
        internal static string PurchaseDone {
            get {
                return ResourceManager.GetString("PurchaseDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买失败, 余额未变动.
        /// </summary>
        internal static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商店消费记录统计:.
        /// </summary>
        internal static string PurchaseHistorySummary {
            get {
                return ResourceManager.GetString("PurchaseHistorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评测发布失败: {0}.
        /// </summary>
        internal static string RecommendPublishFailed {
            get {
                return ResourceManager.GetString("RecommendPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评测发布成功.
        /// </summary>
        internal static string RecommendPublishSuccess {
            get {
                return ResourceManager.GetString("RecommendPublishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅限好友.
        /// </summary>
        internal static string ReplayFriend {
            get {
                return ResourceManager.GetString("ReplayFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数错误 1 私密 2 好友 3 公开.
        /// </summary>
        internal static string ReplayPrivacyError {
            get {
                return ResourceManager.GetString("ReplayPrivacyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私密.
        /// </summary>
        internal static string ReplayPrivate {
            get {
                return ResourceManager.GetString("ReplayPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公开.
        /// </summary>
        internal static string ReplayPublic {
            get {
                return ResourceManager.GetString("ReplayPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该查询未传回任何结果.
        /// </summary>
        internal static string SearchResultEmpty {
            get {
                return ResourceManager.GetString("SearchResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID | 名称.
        /// </summary>
        internal static string SearchResultTitle {
            get {
                return ResourceManager.GetString("SearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送好友请求至 {0} : {1}.
        /// </summary>
        internal static string SendBotFriendRequest {
            get {
                return ResourceManager.GetString("SendBotFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结算货币设置: {0}.
        /// </summary>
        internal static string SetCurrentCountry {
            get {
                return ResourceManager.GetString("SetCurrentCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} == NULL.
        /// </summary>
        internal static string SomethingIsNull {
            get {
                return ResourceManager.GetString("SomethingIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamSaleEvent 为 Null, 该 Bot 可能尚未开启 AutoSteamSaleEvent.
        /// </summary>
        internal static string SteamSaleEventIsNull {
            get {
                return ResourceManager.GetString("SteamSaleEventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - {0}/{1} {2} {3:F2} {4}.
        /// </summary>
        internal static string StoreItem {
            get {
                return ResourceManager.GetString("StoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}: {1}.
        /// </summary>
        internal static string StoreItemHeader {
            get {
                return ResourceManager.GetString("StoreItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到商店页.
        /// </summary>
        internal static string StorePageNotFound {
            get {
                return ResourceManager.GetString("StorePageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - 链接: {0}.
        /// </summary>
        internal static string SubLink {
            get {
                return ResourceManager.GetString("SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - 名称: {0}.
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    - 尺寸: {0:0.000} KB.
        /// </summary>
        internal static string SubSize {
            get {
                return ResourceManager.GetString("SubSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未加入.
        /// </summary>
        internal static string Unjoined {
            get {
                return ResourceManager.GetString("Unjoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件更新失败, 压缩包内容解析失败.
        /// </summary>
        internal static string UpdateFiledWithZip {
            get {
                return ResourceManager.GetString("UpdateFiledWithZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件更新完成, 重启ASF即可应用, 如果不兼容请更新ASF版本.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以使用命令 ASFEUPDATE / AU 自动更新插件.
        /// </summary>
        internal static string UpdateTips {
            get {
                return ResourceManager.GetString("UpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 让BotA添加BotB为好友.
        /// </summary>
        internal static string UsageADDBOTFRIEND {
            get {
                return ResourceManager.GetString("UsageADDBOTFRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加购物车, 仅能使用SubID和BundleID.
        /// </summary>
        internal static string UsageADDCART {
            get {
                return ResourceManager.GetString("UsageADDCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加愿望单.
        /// </summary>
        internal static string UsageADDWISHLIST {
            get {
                return ResourceManager.GetString("UsageADDWISHLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取 APP 信息, 无法获取锁区游戏信息, 仅支持APP.
        /// </summary>
        internal static string UsageAPPDETAIL {
            get {
                return ResourceManager.GetString("UsageAPPDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看指令说明.
        /// </summary>
        internal static string UsageASFEHELP {
            get {
                return ResourceManager.GetString("UsageASFEHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看 ASFEnhance 的版本.
        /// </summary>
        internal static string UsageASFENHANCE {
            get {
                return ResourceManager.GetString("UsageASFENHANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动更新 ASFEnhance 到最新版本 (需要手动重启 ASF).
        /// </summary>
        internal static string UsageASFEUPDATE {
            get {
                return ResourceManager.GetString("UsageASFEUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查 ASFEnhance 的最新版本.
        /// </summary>
        internal static string UsageASFEVERSION {
            get {
                return ResourceManager.GetString("UsageASFEVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看机器人购物车.
        /// </summary>
        internal static string UsageCART {
            get {
                return ResourceManager.GetString("UsageCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取购物车可用结算区域(跟账号钱包和当前 IP 所在地有关).
        /// </summary>
        internal static string UsageCARTCOUNTRY {
            get {
                return ResourceManager.GetString("UsageCARTCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空购物车.
        /// </summary>
        internal static string UsageCARTRESET {
            get {
                return ResourceManager.GetString("UsageCARTRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查游戏关注/愿望单情况.
        /// </summary>
        internal static string UsageCHECK {
            get {
                return ResourceManager.GetString("UsageCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除新物品和新留言通知.
        /// </summary>
        internal static string UsageCLEARNOTIFICATION {
            get {
                return ResourceManager.GetString("UsageCLEARNOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看已关注的鉴赏家列表.
        /// </summary>
        internal static string UsageCURATORLIST {
            get {
                return ResourceManager.GetString("UsageCURATORLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除评测.
        /// </summary>
        internal static string UsageDELETERECOMMENT {
            get {
                return ResourceManager.GetString("UsageDELETERECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取账户中的电子邮件偏好选项.
        /// </summary>
        internal static string UsageEMAILOPTION {
            get {
                return ResourceManager.GetString("UsageEMAILOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 秒后触发 ASF 探索队列任务.
        /// </summary>
        internal static string UsageEXPLORER {
            get {
                return ResourceManager.GetString("UsageEXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注指定鉴赏家.
        /// </summary>
        internal static string UsageFOLLOWCURATOR {
            get {
                return ResourceManager.GetString("UsageFOLLOWCURATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注游戏.
        /// </summary>
        internal static string UsageFOLLOWGAME {
            get {
                return ResourceManager.GetString("UsageFOLLOWGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取账户中的免费 Sub License 列表.
        /// </summary>
        internal static string UsageFREELICENSES {
            get {
                return ResourceManager.GetString("UsageFREELICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看好友代码.
        /// </summary>
        internal static string UsageFRIENDCODE {
            get {
                return ResourceManager.GetString("UsageFRIENDCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看机器人的群组列表.
        /// </summary>
        internal static string UsageGROUPLIST {
            get {
                return ResourceManager.GetString("UsageGROUPLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入指定群组.
        /// </summary>
        internal static string UsageJOINGROUP {
            get {
                return ResourceManager.GetString("UsageJOINGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文本提取 key.
        /// </summary>
        internal static string UsageKEY {
            get {
                return ResourceManager.GetString("UsageKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离开指定群组.
        /// </summary>
        internal static string UsageLEAVEGROUP {
            get {
                return ResourceManager.GetString("UsageLEAVEGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取账户中的所有 License 列表.
        /// </summary>
        internal static string UsageLICENSES {
            get {
                return ResourceManager.GetString("UsageLICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看个人资料.
        /// </summary>
        internal static string UsagePROFILE {
            get {
                return ResourceManager.GetString("UsagePROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看个人资料链接.
        /// </summary>
        internal static string UsagePROFILELINK {
            get {
                return ResourceManager.GetString("UsagePROFILELINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发布评测, APPID &gt; 0 给好评, AppID &lt; 0 给差评.
        /// </summary>
        internal static string UsagePUBLISHRECOMMENT {
            get {
                return ResourceManager.GetString("UsagePUBLISHRECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结算机器人的购物车, 只能为机器人自己购买 (使用 Steam 钱包余额结算).
        /// </summary>
        internal static string UsagePURCHASE {
            get {
                return ResourceManager.GetString("UsagePURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结算机器人 A 的购物车, 发送礼物给机器人 B (使用 Steam 钱包余额结算).
        /// </summary>
        internal static string UsagePURCHASEGIFT {
            get {
                return ResourceManager.GetString("UsagePURCHASEGIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取商店消费历史记录.
        /// </summary>
        internal static string UsagePURCHASEHISTORY {
            get {
                return ResourceManager.GetString("UsagePURCHASEHISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除账户中所有的 Demo License.
        /// </summary>
        internal static string UsageREMOVEDEMOS {
            get {
                return ResourceManager.GetString("UsageREMOVEDEMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除账户中指定的 Sub License.
        /// </summary>
        internal static string UsageREMOVELICENSES {
            get {
                return ResourceManager.GetString("UsageREMOVELICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除愿望单.
        /// </summary>
        internal static string UsageREMOVEWISHLIST {
            get {
                return ResourceManager.GetString("UsageREMOVEWISHLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求游戏内测访问权限.
        /// </summary>
        internal static string UsageREQUESTACCESS {
            get {
                return ResourceManager.GetString("UsageREQUESTACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索商店.
        /// </summary>
        internal static string UsageSEARCH {
            get {
                return ResourceManager.GetString("UsageSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购物车改区,可以用CARTCOUNTRY命令获取当前可选的CountryCode(仍然有 Bug).
        /// </summary>
        internal static string UsageSETCOUNTRY {
            get {
                return ResourceManager.GetString("UsageSETCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置账户中的电子邮件偏好选项.
        /// </summary>
        internal static string UsageSETEMAILOPTION {
            get {
                return ResourceManager.GetString("UsageSETEMAILOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看 steamID.
        /// </summary>
        internal static string UsageSTEAMID {
            get {
                return ResourceManager.GetString("UsageSTEAMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询商店 SUB, 支持APP/SUB/BUNDLE.
        /// </summary>
        internal static string UsageSUBS {
            get {
                return ResourceManager.GetString("UsageSUBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看交易链接.
        /// </summary>
        internal static string UsageTRADELINK {
            get {
                return ResourceManager.GetString("UsageTRADELINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消关注指定鉴赏家.
        /// </summary>
        internal static string UsageUNFOLLOWCURATOR {
            get {
                return ResourceManager.GetString("UsageUNFOLLOWCURATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消关注游戏.
        /// </summary>
        internal static string UsageUNFOLLOWGAME {
            get {
                return ResourceManager.GetString("UsageUNFOLLOWGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 版本: {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是有效的URL.
        /// </summary>
        internal static string ViewPageUrlNotValid {
            get {
                return ResourceManager.GetString("ViewPageUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钱包区域未知.
        /// </summary>
        internal static string WalletAreaUnknown {
            get {
                return ResourceManager.GetString("WalletAreaUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注的发行商或开发者发行了新产品时.
        /// </summary>
        internal static string WhenFollowPublisherRelease {
            get {
                return ResourceManager.GetString("WhenFollowPublisherRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到游戏活动通知时.
        /// </summary>
        internal static string WhenGameEventNotification {
            get {
                return ResourceManager.GetString("WhenGameEventNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注或收藏的青睐之光提交项目发行时.
        /// </summary>
        internal static string WhenGreenLightRelease {
            get {
                return ResourceManager.GetString("WhenGreenLightRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到社区奖励时.
        /// </summary>
        internal static string WhenReceiveCommunityReward {
            get {
                return ResourceManager.GetString("WhenReceiveCommunityReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到鉴赏家副本时.
        /// </summary>
        internal static string WhenReceiveCuratorReview {
            get {
                return ResourceManager.GetString("WhenReceiveCuratorReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 季节性的促销特惠开始时.
        /// </summary>
        internal static string WhenSaleEvent {
            get {
                return ResourceManager.GetString("WhenSaleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 愿望单上的一项物品享有折扣时.
        /// </summary>
        internal static string WhenWishlistDiscount {
            get {
                return ResourceManager.GetString("WhenWishlistDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 愿望单上的一件未发行物品发行时.
        /// </summary>
        internal static string WhenWishlistRelease {
            get {
                return ResourceManager.GetString("WhenWishlistRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
