//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFEnhance.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFEnhance.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {1} 接受来自 {0} 的好友请求 的本地化字符串。
        /// </summary>
        internal static string AcceptFriendRequest {
            get {
                return ResourceManager.GetString("AcceptFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubID | 名称 (仅显示免费Sub) 的本地化字符串。
        /// </summary>
        internal static string AccountFreeSubTitle {
            get {
                return ResourceManager.GetString("AccountFreeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到账户中的免费 Demo Sub 的本地化字符串。
        /// </summary>
        internal static string AccountSubDemoSubNotFount {
            get {
                return ResourceManager.GetString("AccountSubDemoSubNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免费赠送 的本地化字符串。
        /// </summary>
        internal static string AccountSubFree {
            get {
                return ResourceManager.GetString("AccountSubFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 礼物/玩家通行证 的本地化字符串。
        /// </summary>
        internal static string AccountSubGift {
            get {
                return ResourceManager.GetString("AccountSubGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的参数 的本地化字符串。
        /// </summary>
        internal static string AccountSubInvalidArg {
            get {
                return ResourceManager.GetString("AccountSubInvalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} | {1} 的本地化字符串。
        /// </summary>
        internal static string AccountSubItem {
            get {
                return ResourceManager.GetString("AccountSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未拥有该Sub 的本地化字符串。
        /// </summary>
        internal static string AccountSubNotOwn {
            get {
                return ResourceManager.GetString("AccountSubNotOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除了 {0} 个 Demo 的本地化字符串。
        /// </summary>
        internal static string AccountSubRemovedDemos {
            get {
                return ResourceManager.GetString("AccountSubRemovedDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 {0} {1} 的本地化字符串。
        /// </summary>
        internal static string AccountSubRemovedItem {
            get {
                return ResourceManager.GetString("AccountSubRemovedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零售 的本地化字符串。
        /// </summary>
        internal static string AccountSubRetail {
            get {
                return ResourceManager.GetString("AccountSubRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam 商店 的本地化字符串。
        /// </summary>
        internal static string AccountSubStore {
            get {
                return ResourceManager.GetString("AccountSubStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 | 名称 的本地化字符串。
        /// </summary>
        internal static string AccountSubTitle {
            get {
                return ResourceManager.GetString("AccountSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ??? 的本地化字符串。
        /// </summary>
        internal static string AccountSubUnknown {
            get {
                return ResourceManager.GetString("AccountSubUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加好友失败 的本地化字符串。
        /// </summary>
        internal static string AddFriendFailed {
            get {
                return ResourceManager.GetString("AddFriendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加好友成功 的本地化字符串。
        /// </summary>
        internal static string AddFriendSuccess {
            get {
                return ResourceManager.GetString("AddFriendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定游戏, 统计所有游戏 的本地化字符串。
        /// </summary>
        internal static string AllPlayTimeInfo {
            get {
                return ResourceManager.GetString("AllPlayTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经是最新版本, 无需更新插件 的本地化字符串。
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 标签: {0} 的本地化字符串。
        /// </summary>
        internal static string AppCategories {
            get {
                return ResourceManager.GetString("AppCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发售 的本地化字符串。
        /// </summary>
        internal static string AppComingSoon {
            get {
                return ResourceManager.GetString("AppComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可购买 的本地化字符串。
        /// </summary>
        internal static string AppDelisted {
            get {
                return ResourceManager.GetString("AppDelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string AppDetailName {
            get {
                return ResourceManager.GetString("AppDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string AppDetailResult {
            get {
                return ResourceManager.GetString("AppDetailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 开发商: {0} 的本地化字符串。
        /// </summary>
        internal static string AppDevelopers {
            get {
                return ResourceManager.GetString("AppDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 折扣: -{0}% {1} 的本地化字符串。
        /// </summary>
        internal static string AppDiscount {
            get {
                return ResourceManager.GetString("AppDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - DLC: {0} 的本地化字符串。
        /// </summary>
        internal static string AppDlcInfo {
            get {
                return ResourceManager.GetString("AppDlcInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 游戏本体: {0} {1} 的本地化字符串。
        /// </summary>
        internal static string AppFullGame {
            get {
                return ResourceManager.GetString("AppFullGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 分类: {0} 的本地化字符串。
        /// </summary>
        internal static string AppGenres {
            get {
                return ResourceManager.GetString("AppGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已申请 的本地化字符串。
        /// </summary>
        internal static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Metacritic 评分: {0} 的本地化字符串。
        /// </summary>
        internal static string AppMetacriticScore {
            get {
                return ResourceManager.GetString("AppMetacriticScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 折扣: 未打折 的本地化字符串。
        /// </summary>
        internal static string AppNoDiscount {
            get {
                return ResourceManager.GetString("AppNoDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 发型商: {0} 的本地化字符串。
        /// </summary>
        internal static string AppPublishers {
            get {
                return ResourceManager.GetString("AppPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 发售日期: {0} 的本地化字符串。
        /// </summary>
        internal static string AppReleasedDate {
            get {
                return ResourceManager.GetString("AppReleasedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -  [{0}] 的本地化字符串。
        /// </summary>
        internal static string AppReleasedDateEx {
            get {
                return ResourceManager.GetString("AppReleasedDateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 简介: {0} 的本地化字符串。
        /// </summary>
        internal static string AppShortDescription {
            get {
                return ResourceManager.GetString("AppShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Steam 评价数量: {0} 的本地化字符串。
        /// </summary>
        internal static string AppSteamRecommended {
            get {
                return ResourceManager.GetString("AppSteamRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Sub/{0} {1} 的本地化字符串。
        /// </summary>
        internal static string AppSubInfo {
            get {
                return ResourceManager.GetString("AppSubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 支持平台: Win{0} Mac{1} Linux{2} 的本地化字符串。
        /// </summary>
        internal static string AppSupportedPlatforms {
            get {
                return ResourceManager.GetString("AppSupportedPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 类型: {0} 的本地化字符串。
        /// </summary>
        internal static string AppType {
            get {
                return ResourceManager.GetString("AppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLC 的本地化字符串。
        /// </summary>
        internal static string AppTypeDLC {
            get {
                return ResourceManager.GetString("AppTypeDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 / 软件 的本地化字符串。
        /// </summary>
        internal static string AppTypeGame {
            get {
                return ResourceManager.GetString("AppTypeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        internal static string AppTypeMusic {
            get {
                return ResourceManager.GetString("AppTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} | {1} 的本地化字符串。
        /// </summary>
        internal static string AreaItem {
            get {
                return ResourceManager.GetString("AreaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} | {1} | * 的本地化字符串。
        /// </summary>
        internal static string AreaItemCurrent {
            get {
                return ResourceManager.GetString("AreaItemCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数为空 的本地化字符串。
        /// </summary>
        internal static string ArgsIsEmpty {
            get {
                return ResourceManager.GetString("ArgsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误, {0} 必须为整数 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotInteger {
            get {
                return ResourceManager.GetString("ArgumentNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEnhanceDevFuture配置项已经过时, 请根据文档修改 的本地化字符串。
        /// </summary>
        internal static string ASFEConfigWarning {
            get {
                return ResourceManager.GetString("ASFEConfigWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFECurrentVersion {
            get {
                return ResourceManager.GetString("ASFECurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEnhance&apos;s Curator 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceCurator {
            get {
                return ResourceManager.GetString("ASFEnhanceCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEnhance&apos;s Group 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceGroup {
            get {
                return ResourceManager.GetString("ASFEnhanceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEOnlineVersion {
            get {
                return ResourceManager.GetString("ASFEOnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEPluginVersion {
            get {
                return ResourceManager.GetString("ASFEPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ASFEUPDATE / AU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string ASFEUpdateTips {
            get {
                return ResourceManager.GetString("ASFEUpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ASFEVERSION / AV 检查插件更新 的本地化字符串。
        /// </summary>
        internal static string ASFEVersionTips {
            get {
                return ResourceManager.GetString("ASFEVersionTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 附件:  的本地化字符串。
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 | 区域名称 | 当前区域 的本地化字符串。
        /// </summary>
        internal static string AvailableAreaHeader {
            get {
                return ResourceManager.GetString("AvailableAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区封禁: {0} 的本地化字符串。
        /// </summary>
        internal static string BanCommunity {
            get {
                return ResourceManager.GetString("BanCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市场封禁: {0} 的本地化字符串。
        /// </summary>
        internal static string BanEconomy {
            get {
                return ResourceManager.GetString("BanEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏封禁: {0} 的本地化字符串。
        /// </summary>
        internal static string BanGame {
            get {
                return ResourceManager.GetString("BanGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} 个封禁 的本地化字符串。
        /// </summary>
        internal static string BanGameCount {
            get {
                return ResourceManager.GetString("BanGameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamId: {0} 的本地化字符串。
        /// </summary>
        internal static string BanSteamId {
            get {
                return ResourceManager.GetString("BanSteamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAC封禁: {0} 的本地化字符串。
        /// </summary>
        internal static string BanVAC {
            get {
                return ResourceManager.GetString("BanVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} 个封禁, 最后封禁于 {1} 天前 的本地化字符串。
        /// </summary>
        internal static string BanVACCount {
            get {
                return ResourceManager.GetString("BanVACCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法添加自己为好友 的本地化字符串。
        /// </summary>
        internal static string CanNotAddMyself {
            get {
                return ResourceManager.GetString("CanNotAddMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应为空 的本地化字符串。
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 类型无效 [SUB|BUNDLE] 的本地化字符串。
        /// </summary>
        internal static string CartInvalidType {
            get {
                return ResourceManager.GetString("CartInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车是空的 的本地化字符串。
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0} {1} {2:F2} 的本地化字符串。
        /// </summary>
        internal static string CartItemInfo {
            get {
                return ResourceManager.GetString("CartItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作为礼物购买: {0} 的本地化字符串。
        /// </summary>
        internal static string CartPurchaseGift {
            get {
                return ResourceManager.GetString("CartPurchaseGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为自己购买: {0} 的本地化字符串。
        /// </summary>
        internal static string CartPurchaseSelf {
            get {
                return ResourceManager.GetString("CartPurchaseSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空购物车: {0} 的本地化字符串。
        /// </summary>
        internal static string CartResetResult {
            get {
                return ResourceManager.GetString("CartResetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车总额: {0:F2} {1} 的本地化字符串。
        /// </summary>
        internal static string CartTotalPrice {
            get {
                return ResourceManager.GetString("CartTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改头像失败 的本地化字符串。
        /// </summary>
        internal static string ChangeAvatarFailed {
            get {
                return ResourceManager.GetString("ChangeAvatarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改头像成功 的本地化字符串。
        /// </summary>
        internal static string ChangeAvatarSuccess {
            get {
                return ResourceManager.GetString("ChangeAvatarSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} | 参数错误 的本地化字符串。
        /// </summary>
        internal static string CheckGameItemError {
            get {
                return ResourceManager.GetString("CheckGameItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} | {1} 的本地化字符串。
        /// </summary>
        internal static string CheckGameItemFailed {
            get {
                return ResourceManager.GetString("CheckGameItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} | {1} | {2} | {3} | {4} 的本地化字符串。
        /// </summary>
        internal static string CheckGameItemSuccess {
            get {
                return ResourceManager.GetString("CheckGameItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppID | 游戏名 | 已拥有 | 愿望单 | 关注 的本地化字符串。
        /// </summary>
        internal static string CheckGameListTitle {
            get {
                return ResourceManager.GetString("CheckGameListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份已经自动清理 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份清理失败 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam商店的Cookies: 的本地化字符串。
        /// </summary>
        internal static string ClientCookies {
            get {
                return ResourceManager.GetString("ClientCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令帮助: 的本地化字符串。
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到相关命令的帮助 的本地化字符串。
        /// </summary>
        internal static string CommandHelpCmdNotFound {
            get {
                return ResourceManager.GetString("CommandHelpCmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0} {1} : {2} 的本地化字符串。
        /// </summary>
        internal static string CommandHelpNoShortName {
            get {
                return ResourceManager.GetString("CommandHelpNoShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无描述 的本地化字符串。
        /// </summary>
        internal static string CommandHelpNoUsage {
            get {
                return ResourceManager.GetString("CommandHelpNoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  * 可用缩写 : {0} 的本地化字符串。
        /// </summary>
        internal static string CommandHelpWithShortName {
            get {
                return ResourceManager.GetString("CommandHelpWithShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string CookieItem {
            get {
                return ResourceManager.GetString("CookieItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} / {1} 个徽章合成成功 的本地化字符串。
        /// </summary>
        internal static string CraftBadgeResult {
            get {
                return ResourceManager.GetString("CraftBadgeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClanID | 鉴赏家名称 | 关注人数 的本地化字符串。
        /// </summary>
        internal static string CuratorListTitle {
            get {
                return ResourceManager.GetString("CuratorListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前通知设定: 的本地化字符串。
        /// </summary>
        internal static string CurrentNotificationSetting {
            get {
                return ResourceManager.GetString("CurrentNotificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 是 NULL 的本地化字符串。
        /// </summary>
        internal static string DataIsNull {
            get {
                return ResourceManager.GetString("DataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除了 {0} 个好友 的本地化字符串。
        /// </summary>
        internal static string DeleteFriendSuccess {
            get {
                return ResourceManager.GetString("DeleteFriendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 {0} 的评测:  的本地化字符串。
        /// </summary>
        internal static string DeleteReview {
            get {
                return ResourceManager.GetString("DeleteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 描述: {0} 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEhance 开发者特性已开启 的本地化字符串。
        /// </summary>
        internal static string DevFeatureEnabledWarning {
            get {
                return ResourceManager.GetString("DevFeatureEnabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未启用 ASFEnhance.DevFeature , 该命令不可用 的本地化字符串。
        /// </summary>
        internal static string DevFeatureNotEnabled {
            get {
                return ResourceManager.GetString("DevFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载插件失败! 的本地化字符串。
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载头像图片失败 的本地化字符串。
        /// </summary>
        internal static string DownloadImageFailed {
            get {
                return ResourceManager.GetString("DownloadImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用邮件通知 的本地化字符串。
        /// </summary>
        internal static string EnableEmailNotification {
            get {
                return ResourceManager.GetString("EnableEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Access: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogAccess {
            get {
                return ResourceManager.GetString("ErrorLogAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - ASF 版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogASFVersion {
            get {
                return ResourceManager.GetString("ErrorLogASFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 错误消息: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogErrorMessage {
            get {
                return ResourceManager.GetString("ErrorLogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 错误类型: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogErrorName {
            get {
                return ResourceManager.GetString("ErrorLogErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 原始消息: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogOriginMessage {
            get {
                return ResourceManager.GetString("ErrorLogOriginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogPluginVersion {
            get {
                return ResourceManager.GetString("ErrorLogPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFenhance 遇到错误, 日志如下 的本地化字符串。
        /// </summary>
        internal static string ErrorLogTitle {
            get {
                return ResourceManager.GetString("ErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未同意 ASFEnhance.EULA , 该命令不可用 的本地化字符串。
        /// </summary>
        internal static string EulaCmdUnavilable {
            get {
                return ResourceManager.GetString("EulaCmdUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未同意 ASFEnhance.EULA , 无法使用IPC功能 的本地化字符串。
        /// </summary>
        internal static string EulaFeatureUnavilable {
            get {
                return ResourceManager.GetString("EulaFeatureUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 尚未同意 EULA , 部分命令已禁用 的本地化字符串。
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领取每日贴纸: {0} 的本地化字符串。
        /// </summary>
        internal static string EventClaimItem {
            get {
                return ResourceManager.GetString("EventClaimItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日探索队列: {0} 的本地化字符串。
        /// </summary>
        internal static string EventQueue {
            get {
                return ResourceManager.GetString("EventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取投票信息失败 的本地化字符串。
        /// </summary>
        internal static string EventReadBadgeStatusFailed {
            get {
                return ResourceManager.GetString("EventReadBadgeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节日活动已完成 的本地化字符串。
        /// </summary>
        internal static string EventTaskComplete {
            get {
                return ResourceManager.GetString("EventTaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Award 投票: {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string EventVoteResponse {
            get {
                return ResourceManager.GetString("EventVoteResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索队列任务将尽快触发 的本地化字符串。
        /// </summary>
        internal static string ExplorerStart {
            get {
                return ResourceManager.GetString("ExplorerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡单完成 的本地化字符串。
        /// </summary>
        internal static string FakePurchaseDone {
            get {
                return ResourceManager.GetString("FakePurchaseDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取App信息失败, 可能AppID错误, 或者锁区 的本地化字符串。
        /// </summary>
        internal static string FetchAppDetailFailed {
            get {
                return ResourceManager.GetString("FetchAppDetailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 {0} 失败 的本地化字符串。
        /// </summary>
        internal static string FetchDataFailed {
            get {
                return ResourceManager.GetString("FetchDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取可用游戏头像失败 的本地化字符串。
        /// </summary>
        internal static string GameAvatarGameAvatarIsEmpty {
            get {
                return ResourceManager.GetString("GameAvatarGameAvatarIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取游戏列表失败 的本地化字符串。
        /// </summary>
        internal static string GameAvatarGameNotFound {
            get {
                return ResourceManager.GetString("GameAvatarGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是有效的AvatarId 的本地化字符串。
        /// </summary>
        internal static string GameAvatarInvalidAvatarId {
            get {
                return ResourceManager.GetString("GameAvatarInvalidAvatarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是有效的AppId 的本地化字符串。
        /// </summary>
        internal static string GameAvatarInvalidGameId {
            get {
                return ResourceManager.GetString("GameAvatarInvalidGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 类型无效 [APP|SUB|BUNDLE] 的本地化字符串。
        /// </summary>
        internal static string GameInvalidType {
            get {
                return ResourceManager.GetString("GameInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取在线汇率失败 的本地化字符串。
        /// </summary>
        internal static string GetExchangeRateFailed {
            get {
                return ResourceManager.GetString("GetExchangeRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取个人资料失败 的本地化字符串。
        /// </summary>
        internal static string GetProfileFailed {
            get {
                return ResourceManager.GetString("GetProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取插件发行版信息失败! 的本地化字符串。
        /// </summary>
        internal static string GetReleaseInfoFailed {
            get {
                return ResourceManager.GetString("GetReleaseInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取商店名称出错 的本地化字符串。
        /// </summary>
        internal static string GetStoreNameFailed {
            get {
                return ResourceManager.GetString("GetStoreNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 {0} 发送 的本地化字符串。
        /// </summary>
        internal static string GifteeName {
            get {
                return ResourceManager.GetString("GifteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Version {1} 的本地化字符串。
        /// </summary>
        internal static string GiftMessage {
            get {
                return ResourceManager.GetString("GiftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send by {0} 的本地化字符串。
        /// </summary>
        internal static string GiftSignature {
            get {
                return ResourceManager.GetString("GiftSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未加入任何群组 的本地化字符串。
        /// </summary>
        internal static string GroupListEmpty {
            get {
                return ResourceManager.GetString("GroupListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} | {1} | {2} 的本地化字符串。
        /// </summary>
        internal static string GroupListItem {
            get {
                return ResourceManager.GetString("GroupListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No | 群组名称 | 群组ID 的本地化字符串。
        /// </summary>
        internal static string GroupListTitle {
            get {
                return ResourceManager.GetString("GroupListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ ]: 可选参数, &lt; &gt;: 数组(使用,分隔) 的本地化字符串。
        /// </summary>
        internal static string HelpArgsExplain {
            get {
                return ResourceManager.GetString("HelpArgsExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 无效的AppId 的本地化字符串。
        /// </summary>
        internal static string InvalidAppId {
            get {
                return ResourceManager.GetString("InvalidAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加入 的本地化字符串。
        /// </summary>
        internal static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入群组 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到结果 的本地化字符串。
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 schinese 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出群组: {0} 的本地化字符串。
        /// </summary>
        internal static string LeaveGroup {
            get {
                return ResourceManager.GetString("LeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无参数 的本地化字符串。
        /// </summary>
        internal static string NoArgs {
            get {
                return ResourceManager.GetString("NoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用区域选项, 结算货币为钱包货币 的本地化字符串。
        /// </summary>
        internal static string NoAvailableArea {
            get {
                return ResourceManager.GetString("NoAvailableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次需要提供账单地址, 但是尚未配置可用地址, 无法激活 的本地化字符串。
        /// </summary>
        internal static string NoAvilableAddressError {
            get {
                return ResourceManager.GetString("NoAvilableAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可合成徽章 的本地化字符串。
        /// </summary>
        internal static string NoCraftableBadge {
            get {
                return ResourceManager.GetString("NoCraftableBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有好友可以删除 的本地化字符串。
        /// </summary>
        internal static string NoFriend {
            get {
                return ResourceManager.GetString("NoFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我收到了好友邀请 的本地化字符串。
        /// </summary>
        internal static string NooFriendInvite {
            get {
                return ResourceManager.GetString("NooFriendInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有大型特卖 的本地化字符串。
        /// </summary>
        internal static string NooMajorSale {
            get {
                return ResourceManager.GetString("NooMajorSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我库存中收到了新物品 的本地化字符串。
        /// </summary>
        internal static string NooNewItem {
            get {
                return ResourceManager.GetString("NooNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我收到了一个新的交易报价 的本地化字符串。
        /// </summary>
        internal static string NooNewTradeOffer {
            get {
                return ResourceManager.GetString("NooNewTradeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我收到了礼物 的本地化字符串。
        /// </summary>
        internal static string NooReceivedGift {
            get {
                return ResourceManager.GetString("NooReceivedGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我订阅的讨论区有回复 的本地化字符串。
        /// </summary>
        internal static string NooReceivedReply {
            get {
                return ResourceManager.GetString("NooReceivedReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我收到了 Steam 客服的回复 的本地化字符串。
        /// </summary>
        internal static string NooSteamSupport {
            get {
                return ResourceManager.GetString("NooSteamSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我收到了 Steam 回合通知 的本地化字符串。
        /// </summary>
        internal static string NooSteamTurn {
            get {
                return ResourceManager.GetString("NooSteamTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 愿望单中的某件物品有折扣 的本地化字符串。
        /// </summary>
        internal static string NooWishlistOnSale {
            get {
                return ResourceManager.GetString("NooWishlistOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 无游玩时长数据 的本地化字符串。
        /// </summary>
        internal static string NoPlayTimeInfo {
            get {
                return ResourceManager.GetString("NoPlayTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未关注任何鉴赏家 的本地化字符串。
        /// </summary>
        internal static string NotFollowAnyCurator {
            get {
                return ResourceManager.GetString("NotFollowAnyCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未查询到用户信息 的本地化字符串。
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 客户端通知, 手机应用通知 的本地化字符串。
        /// </summary>
        internal static string NTAll {
            get {
                return ResourceManager.GetString("NTAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 手机应用通知 的本地化字符串。
        /// </summary>
        internal static string NtMobile {
            get {
                return ResourceManager.GetString("NtMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 客户端通知 的本地化字符串。
        /// </summary>
        internal static string NTSteamClient {
            get {
                return ResourceManager.GetString("NTSteamClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML解析失败! 的本地化字符串。
        /// </summary>
        internal static string ParseHtmlFailed {
            get {
                return ResourceManager.GetString("ParseHtmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 游玩时长 {2:F2}h 2周游玩时长 {3:F2}h [{1}] 的本地化字符串。
        /// </summary>
        internal static string PlayTimeItem {
            get {
                return ResourceManager.GetString("PlayTimeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 Chr_, 联系方式 chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 徽章: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileBadges {
            get {
                return ResourceManager.GetString("ProfileBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好友: {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string ProfileFriends {
            get {
                return ResourceManager.GetString("ProfileFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileGames {
            get {
                return ResourceManager.GetString("ProfileGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileGroups {
            get {
                return ResourceManager.GetString("ProfileGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指南: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileGuide {
            get {
                return ResourceManager.GetString("ProfileGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人资料: 的本地化字符串。
        /// </summary>
        internal static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艺术作品: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileImages {
            get {
                return ResourceManager.GetString("ProfileImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileLevel {
            get {
                return ResourceManager.GetString("ProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileNickname {
            get {
                return ResourceManager.GetString("ProfileNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到个人资料 的本地化字符串。
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评测: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileRecommended {
            get {
                return ResourceManager.GetString("ProfileRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileScreenshots {
            get {
                return ResourceManager.GetString("ProfileScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileState {
            get {
                return ResourceManager.GetString("ProfileState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileVideos {
            get {
                return ResourceManager.GetString("ProfileVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创意工坊: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileWorkshop {
            get {
                return ResourceManager.GetString("ProfileWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车是空的,无需结账 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartFailureEmpty {
            get {
                return ResourceManager.GetString("PurchaseCartFailureEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, FinalizeTransaction 返回值为空 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartFailureFinalizeTransactionIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartFailureFinalizeTransactionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, GetFinalPrice 返回值为空 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartGetFinalPriceIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartGetFinalPriceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, transID 为Null 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartTransIDIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartTransIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买完成, 消费金额: {0} 的本地化字符串。
        /// </summary>
        internal static string PurchaseDone {
            get {
                return ResourceManager.GetString("PurchaseDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, 余额未变动 的本地化字符串。
        /// </summary>
        internal static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 基准汇率 {0} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryAboutBaseRate {
            get {
                return ResourceManager.GetString("PurchaseHistoryAboutBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 计算结果由 {0} 生成, 仅供参考 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryAboutPlugin {
            get {
                return ResourceManager.GetString("PurchaseHistoryAboutPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 在线汇率数据来自 ExchangeRate-API.com 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryAboutRateSource {
            get {
                return ResourceManager.GetString("PurchaseHistoryAboutRateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 汇率数据更新时间: {0:g} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryAboutUpdateTime {
            get {
                return ResourceManager.GetString("PurchaseHistoryAboutUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 额度*1.8 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryCreditMax {
            get {
                return ResourceManager.GetString("PurchaseHistoryCreditMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 额度*1.0 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryCreditMin {
            get {
                return ResourceManager.GetString("PurchaseHistoryCreditMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 外部*1.8 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryExternalMax {
            get {
                return ResourceManager.GetString("PurchaseHistoryExternalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 外部*1.0 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryExternalMin {
            get {
                return ResourceManager.GetString("PurchaseHistoryExternalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据说明: 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryGroupAbout {
            get {
                return ResourceManager.GetString("PurchaseHistoryGroupAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 额度推算(仅供参考): 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryGroupGiftCredit {
            get {
                return ResourceManager.GetString("PurchaseHistoryGroupGiftCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  2.其他类型的消费: 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryGroupOther {
            get {
                return ResourceManager.GetString("PurchaseHistoryGroupOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据统计(仅供参考): 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryGroupStatus {
            get {
                return ResourceManager.GetString("PurchaseHistoryGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  1.按购买类型分类(不含已退款的消费): 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryGroupType {
            get {
                return ResourceManager.GetString("PurchaseHistoryGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 外部消费总和: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryStatusTotalExternalPurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryStatusTotalExternalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 礼物赠送总和: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryStatusTotalGift {
            get {
                return ResourceManager.GetString("PurchaseHistoryStatusTotalGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 有效额度总和: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryStatusTotalPurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryStatusTotalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商店消费记录统计: 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistorySummary {
            get {
                return ResourceManager.GetString("PurchaseHistorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 外部: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeExternal {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 礼物赠送: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeGiftPurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeGiftPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 游戏内购: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeInGamePurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeInGamePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 市场购买: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeMarketPurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeMarketPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 市场出售: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeMarketSelling {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeMarketSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 其他类型: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeOther {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 退款: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeRefunded {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 商店购买: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeStorePurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeStorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 余额: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeWallet {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 余额充值: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistoryTypeWalletPurchase {
            get {
                return ResourceManager.GetString("PurchaseHistoryTypeWalletPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到礼物 {0} 个, 接收成功 {1} 个 的本地化字符串。
        /// </summary>
        internal static string ReceiveGiftResult {
            get {
                return ResourceManager.GetString("ReceiveGiftResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评测发布失败: {0} 的本地化字符串。
        /// </summary>
        internal static string RecommendPublishFailed {
            get {
                return ResourceManager.GetString("RecommendPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评测发布成功 的本地化字符串。
        /// </summary>
        internal static string RecommendPublishSuccess {
            get {
                return ResourceManager.GetString("RecommendPublishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} : {1} 代码 {2} 的本地化字符串。
        /// </summary>
        internal static string RedeemWalletError {
            get {
                return ResourceManager.GetString("RedeemWalletError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册checkout域名失败 的本地化字符串。
        /// </summary>
        internal static string RegisterServiceFailed {
            get {
                return ResourceManager.GetString("RegisterServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不能使用超过 9 个随机数字的号码 的本地化字符串。
        /// </summary>
        internal static string RenameTooBigRandomNumber {
            get {
                return ResourceManager.GetString("RenameTooBigRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅限好友 的本地化字符串。
        /// </summary>
        internal static string ReplayFriend {
            get {
                return ResourceManager.GetString("ReplayFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 1 私密 2 好友 3 公开 的本地化字符串。
        /// </summary>
        internal static string ReplayPrivacyError {
            get {
                return ResourceManager.GetString("ReplayPrivacyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私密 的本地化字符串。
        /// </summary>
        internal static string ReplayPrivate {
            get {
                return ResourceManager.GetString("ReplayPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公开 的本地化字符串。
        /// </summary>
        internal static string ReplayPublic {
            get {
                return ResourceManager.GetString("ReplayPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该查询未传回任何结果 的本地化字符串。
        /// </summary>
        internal static string SearchResultEmpty {
            get {
                return ResourceManager.GetString("SearchResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppID | 名称 的本地化字符串。
        /// </summary>
        internal static string SearchResultTitle {
            get {
                return ResourceManager.GetString("SearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送好友请求至 {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string SendBotFriendRequest {
            get {
                return ResourceManager.GetString("SendBotFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送好友请求成功 的本地化字符串。
        /// </summary>
        internal static string SendFriendRequestSuccess {
            get {
                return ResourceManager.GetString("SendFriendRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功发送 {0} 个请求 的本地化字符串。
        /// </summary>
        internal static string SendRequestSuccess {
            get {
                return ResourceManager.GetString("SendRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算货币设置: {0} 的本地化字符串。
        /// </summary>
        internal static string SetCurrentCountry {
            get {
                return ResourceManager.GetString("SetCurrentCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} == NULL 的本地化字符串。
        /// </summary>
        internal static string SomethingIsNull {
            get {
                return ResourceManager.GetString("SomethingIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamSaleEvent 为 Null, 该 Bot 可能尚未开启 AutoSteamSaleEvent 的本地化字符串。
        /// </summary>
        internal static string SteamSaleEventIsNull {
            get {
                return ResourceManager.GetString("SteamSaleEventIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   - {0}/{1} {2} {3:F2} {4} 的本地化字符串。
        /// </summary>
        internal static string StoreItem {
            get {
                return ResourceManager.GetString("StoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string StoreItemHeader {
            get {
                return ResourceManager.GetString("StoreItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到商店页 的本地化字符串。
        /// </summary>
        internal static string StorePageNotFound {
            get {
                return ResourceManager.GetString("StorePageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 链接: {0} 的本地化字符串。
        /// </summary>
        internal static string SubLink {
            get {
                return ResourceManager.GetString("SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 尺寸: {0:0.000} KB 的本地化字符串。
        /// </summary>
        internal static string SubSize {
            get {
                return ResourceManager.GetString("SubSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计游玩时长: {0:F2}h 2周游玩时长: {1:F2}h 的本地化字符串。
        /// </summary>
        internal static string TotalPlayTimeItem {
            get {
                return ResourceManager.GetString("TotalPlayTimeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功取关 {0} 个鉴赏家, 共计 {1} 个鉴赏家 的本地化字符串。
        /// </summary>
        internal static string UnFollowAllCuratorResult {
            get {
                return ResourceManager.GetString("UnFollowAllCuratorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未加入 的本地化字符串。
        /// </summary>
        internal static string Unjoined {
            get {
                return ResourceManager.GetString("Unjoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新失败, 压缩包内容解析失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFiledWithZip {
            get {
                return ResourceManager.GetString("UpdateFiledWithZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新完成, 重启ASF即可应用, 如果不兼容请更新ASF版本 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以使用命令 ASFEUPDATE / AU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string UpdateTips {
            get {
                return ResourceManager.GetString("UpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让BotA添加BotB为好友 的本地化字符串。
        /// </summary>
        internal static string UsageADDBOTFRIEND {
            get {
                return ResourceManager.GetString("UsageADDBOTFRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加购物车, 仅能使用SubID和BundleID 的本地化字符串。
        /// </summary>
        internal static string UsageADDCART {
            get {
                return ResourceManager.GetString("UsageADDCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让机器人发送好友请求, Text 支持 自定义链接, SteamId, 好友代码 的本地化字符串。
        /// </summary>
        internal static string UsageADDFRIEND {
            get {
                return ResourceManager.GetString("UsageADDFRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加愿望单 的本地化字符串。
        /// </summary>
        internal static string UsageADDWISHLIST {
            get {
                return ResourceManager.GetString("UsageADDWISHLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 占位符 设置机器人昵称, 可用占位符 %dn% %ln% %un% %botn% 不区分大小写 的本地化字符串。
        /// </summary>
        internal static string UsageADVNICKNAME {
            get {
                return ResourceManager.GetString("UsageADVNICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 APP 信息, 无法获取锁区游戏信息, 仅支持APP 的本地化字符串。
        /// </summary>
        internal static string UsageAPPDETAIL {
            get {
                return ResourceManager.GetString("UsageAPPDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看指令说明 的本地化字符串。
        /// </summary>
        internal static string UsageASFEHELP {
            get {
                return ResourceManager.GetString("UsageASFEHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 ASFEnhance 的版本 的本地化字符串。
        /// </summary>
        internal static string UsageASFENHANCE {
            get {
                return ResourceManager.GetString("UsageASFENHANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新 ASFEnhance 到最新版本 (需要手动重启 ASF) 的本地化字符串。
        /// </summary>
        internal static string UsageASFEUPDATE {
            get {
                return ResourceManager.GetString("UsageASFEUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 ASFEnhance 的最新版本 的本地化字符串。
        /// </summary>
        internal static string UsageASFEVERSION {
            get {
                return ResourceManager.GetString("UsageASFEVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看机器人购物车 的本地化字符串。
        /// </summary>
        internal static string UsageCART {
            get {
                return ResourceManager.GetString("UsageCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取购物车可用结算区域(跟账号钱包和当前 IP 所在地有关) 的本地化字符串。
        /// </summary>
        internal static string UsageCARTCOUNTRY {
            get {
                return ResourceManager.GetString("UsageCARTCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空购物车 的本地化字符串。
        /// </summary>
        internal static string UsageCARTRESET {
            get {
                return ResourceManager.GetString("UsageCARTRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查游戏关注/愿望单情况 的本地化字符串。
        /// </summary>
        internal static string UsageCHECK {
            get {
                return ResourceManager.GetString("UsageCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除曾用名 的本地化字符串。
        /// </summary>
        internal static string UsageCLEARALIAS {
            get {
                return ResourceManager.GetString("UsageCLEARALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除新物品和新留言通知 的本地化字符串。
        /// </summary>
        internal static string UsageCLEARNOTIFICATION {
            get {
                return ResourceManager.GetString("UsageCLEARNOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动合成可合成徽章 (一次一级) 的本地化字符串。
        /// </summary>
        internal static string UsageCRAFTBADGE {
            get {
                return ResourceManager.GetString("UsageCRAFTBADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看已关注的鉴赏家列表 的本地化字符串。
        /// </summary>
        internal static string UsageCURATORLIST {
            get {
                return ResourceManager.GetString("UsageCURATORLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有好友 的本地化字符串。
        /// </summary>
        internal static string UsageDELETEALLFRIEND {
            get {
                return ResourceManager.GetString("UsageDELETEALLFRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除机器人的头像(设置为默认头像) 的本地化字符串。
        /// </summary>
        internal static string UsageDELETEAVATAR {
            get {
                return ResourceManager.GetString("UsageDELETEAVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定好友, Text 支持 自定义链接, SteamId, 好友代码 的本地化字符串。
        /// </summary>
        internal static string UsageDELETEFRIEND {
            get {
                return ResourceManager.GetString("UsageDELETEFRIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除评测 的本地化字符串。
        /// </summary>
        internal static string UsageDELETERECOMMENT {
            get {
                return ResourceManager.GetString("UsageDELETERECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取账户中的电子邮件偏好选项 的本地化字符串。
        /// </summary>
        internal static string UsageEMAILOPTION {
            get {
                return ResourceManager.GetString("UsageEMAILOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 秒后触发 ASF 探索队列任务 的本地化字符串。
        /// </summary>
        internal static string UsageEXPLORER {
            get {
                return ResourceManager.GetString("UsageEXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟结算机器人的购物车, 生成一条购买失败的记录, 不会真的结账 的本地化字符串。
        /// </summary>
        internal static string UsageFAKEPURCHASE {
            get {
                return ResourceManager.GetString("UsageFAKEPURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注指定鉴赏家 的本地化字符串。
        /// </summary>
        internal static string UsageFOLLOWCURATOR {
            get {
                return ResourceManager.GetString("UsageFOLLOWCURATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注游戏 的本地化字符串。
        /// </summary>
        internal static string UsageFOLLOWGAME {
            get {
                return ResourceManager.GetString("UsageFOLLOWGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取账户中的免费 Sub License 列表 的本地化字符串。
        /// </summary>
        internal static string UsageFREELICENSES {
            get {
                return ResourceManager.GetString("UsageFREELICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看好友代码 的本地化字符串。
        /// </summary>
        internal static string UsageFRIENDCODE {
            get {
                return ResourceManager.GetString("UsageFRIENDCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据指定 AppID 和 AvatarID 设置机器人的头像 的本地化字符串。
        /// </summary>
        internal static string UsageGAMEAVATAR {
            get {
                return ResourceManager.GetString("UsageGAMEAVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看机器人的群组列表 的本地化字符串。
        /// </summary>
        internal static string UsageGROUPLIST {
            get {
                return ResourceManager.GetString("UsageGROUPLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入指定群组 的本地化字符串。
        /// </summary>
        internal static string UsageJOINGROUP {
            get {
                return ResourceManager.GetString("UsageJOINGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文本提取 key 的本地化字符串。
        /// </summary>
        internal static string UsageKEY {
            get {
                return ResourceManager.GetString("UsageKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离开指定群组 的本地化字符串。
        /// </summary>
        internal static string UsageLEAVEGROUP {
            get {
                return ResourceManager.GetString("UsageLEAVEGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取账户中的所有 License 列表 的本地化字符串。
        /// </summary>
        internal static string UsageLICENSES {
            get {
                return ResourceManager.GetString("UsageLICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看个人资料 的本地化字符串。
        /// </summary>
        internal static string UsagePROFILE {
            get {
                return ResourceManager.GetString("UsagePROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看个人资料链接 的本地化字符串。
        /// </summary>
        internal static string UsagePROFILELINK {
            get {
                return ResourceManager.GetString("UsagePROFILELINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布评测, APPID &gt; 0 给好评, AppID &lt; 0 给差评 的本地化字符串。
        /// </summary>
        internal static string UsagePUBLISHRECOMMENT {
            get {
                return ResourceManager.GetString("UsagePUBLISHRECOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算机器人的购物车, 只能为机器人自己购买 (使用 Steam 钱包余额结算) 的本地化字符串。
        /// </summary>
        internal static string UsagePURCHASE {
            get {
                return ResourceManager.GetString("UsagePURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算机器人 A 的购物车, 发送礼物给机器人 B (使用 Steam 钱包余额结算) 的本地化字符串。
        /// </summary>
        internal static string UsagePURCHASEGIFT {
            get {
                return ResourceManager.GetString("UsagePURCHASEGIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取商店消费历史记录 的本地化字符串。
        /// </summary>
        internal static string UsagePURCHASEHISTORY {
            get {
                return ResourceManager.GetString("UsagePURCHASEHISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置机器人的头像为随机游戏头像 的本地化字符串。
        /// </summary>
        internal static string UsageRANDOMGAMEAVATAR {
            get {
                return ResourceManager.GetString("UsageRANDOMGAMEAVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兑换钱包充值码, 如果需要提供地址信息则自动填入配置文件中的地址 的本地化字符串。
        /// </summary>
        internal static string UsageREDEEMWALLET {
            get {
                return ResourceManager.GetString("UsageREDEEMWALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量兑换钱包充值码, 但是每个机器人只会兑换一个 key 的本地化字符串。
        /// </summary>
        internal static string UsageREDEEMWALLETMULT {
            get {
                return ResourceManager.GetString("UsageREDEEMWALLETMULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除账户中所有的 Demo License 的本地化字符串。
        /// </summary>
        internal static string UsageREMOVEDEMOS {
            get {
                return ResourceManager.GetString("UsageREMOVEDEMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除账户中指定的 Sub License 的本地化字符串。
        /// </summary>
        internal static string UsageREMOVELICENSES {
            get {
                return ResourceManager.GetString("UsageREMOVELICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除愿望单 的本地化字符串。
        /// </summary>
        internal static string UsageREMOVEWISHLIST {
            get {
                return ResourceManager.GetString("UsageREMOVEWISHLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取摘要图片链接 (可以解锁徽章) 的本地化字符串。
        /// </summary>
        internal static string UsageREPLAY {
            get {
                return ResourceManager.GetString("UsageREPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置年度总结可见性, Privacy 1=私密 2=好友可见 3=公开 的本地化字符串。
        /// </summary>
        internal static string UsageREPLAYPRIVACY {
            get {
                return ResourceManager.GetString("UsageREPLAYPRIVACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求游戏内测访问权限 的本地化字符串。
        /// </summary>
        internal static string UsageREQUESTACCESS {
            get {
                return ResourceManager.GetString("UsageREQUESTACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索商店 的本地化字符串。
        /// </summary>
        internal static string UsageSEARCH {
            get {
                return ResourceManager.GetString("UsageSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置机器人头像为给定的网络图片 的本地化字符串。
        /// </summary>
        internal static string UsageSETAVATAR {
            get {
                return ResourceManager.GetString("UsageSETAVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车改区,可以用CARTCOUNTRY命令获取当前可选的CountryCode(仍然有 Bug) 的本地化字符串。
        /// </summary>
        internal static string UsageSETCOUNTRY {
            get {
                return ResourceManager.GetString("UsageSETCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置账户中的电子邮件偏好选项 的本地化字符串。
        /// </summary>
        internal static string UsageSETEMAILOPTION {
            get {
                return ResourceManager.GetString("UsageSETEMAILOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 steamID 的本地化字符串。
        /// </summary>
        internal static string UsageSTEAMID {
            get {
                return ResourceManager.GetString("UsageSTEAMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询商店 SUB, 支持APP/SUB/BUNDLE 的本地化字符串。
        /// </summary>
        internal static string UsageSUBS {
            get {
                return ResourceManager.GetString("UsageSUBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看交易链接 的本地化字符串。
        /// </summary>
        internal static string UsageTRADELINK {
            get {
                return ResourceManager.GetString("UsageTRADELINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消关注所有鉴赏家 的本地化字符串。
        /// </summary>
        internal static string UsageUNFOLLOWALLCURATORS {
            get {
                return ResourceManager.GetString("UsageUNFOLLOWALLCURATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消关注指定鉴赏家 的本地化字符串。
        /// </summary>
        internal static string UsageUNFOLLOWCURATOR {
            get {
                return ResourceManager.GetString("UsageUNFOLLOWCURATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消关注游戏 的本地化字符串。
        /// </summary>
        internal static string UsageUNFOLLOWGAME {
            get {
                return ResourceManager.GetString("UsageUNFOLLOWGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 版本: {0} 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是有效的URL 的本地化字符串。
        /// </summary>
        internal static string ViewPageUrlNotValid {
            get {
                return ResourceManager.GetString("ViewPageUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱包区域未知 的本地化字符串。
        /// </summary>
        internal static string WalletAreaUnknown {
            get {
                return ResourceManager.GetString("WalletAreaUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注的发行商或开发者发行了新产品时 的本地化字符串。
        /// </summary>
        internal static string WhenFollowPublisherRelease {
            get {
                return ResourceManager.GetString("WhenFollowPublisherRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到游戏活动通知时 的本地化字符串。
        /// </summary>
        internal static string WhenGameEventNotification {
            get {
                return ResourceManager.GetString("WhenGameEventNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关注或收藏的青睐之光提交项目发行时 的本地化字符串。
        /// </summary>
        internal static string WhenGreenLightRelease {
            get {
                return ResourceManager.GetString("WhenGreenLightRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到社区奖励时 的本地化字符串。
        /// </summary>
        internal static string WhenReceiveCommunityReward {
            get {
                return ResourceManager.GetString("WhenReceiveCommunityReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到鉴赏家副本时 的本地化字符串。
        /// </summary>
        internal static string WhenReceiveCuratorReview {
            get {
                return ResourceManager.GetString("WhenReceiveCuratorReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 季节性的促销特惠开始时 的本地化字符串。
        /// </summary>
        internal static string WhenSaleEvent {
            get {
                return ResourceManager.GetString("WhenSaleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 愿望单上的一项物品享有折扣时 的本地化字符串。
        /// </summary>
        internal static string WhenWishlistDiscount {
            get {
                return ResourceManager.GetString("WhenWishlistDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 愿望单上的一件未发行物品发行时 的本地化字符串。
        /// </summary>
        internal static string WhenWishlistRelease {
            get {
                return ResourceManager.GetString("WhenWishlistRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
