//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFEnhance.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFEnhance.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经是最新版本, 无需更新插件 的本地化字符串。
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 标签: {0} 的本地化字符串。
        /// </summary>
        internal static string AppCategories {
            get {
                return ResourceManager.GetString("AppCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发售 的本地化字符串。
        /// </summary>
        internal static string AppComingSoon {
            get {
                return ResourceManager.GetString("AppComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可购买 的本地化字符串。
        /// </summary>
        internal static string AppDelisted {
            get {
                return ResourceManager.GetString("AppDelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string AppDetailName {
            get {
                return ResourceManager.GetString("AppDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string AppDetailResult {
            get {
                return ResourceManager.GetString("AppDetailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 开发商: {0} 的本地化字符串。
        /// </summary>
        internal static string AppDevelopers {
            get {
                return ResourceManager.GetString("AppDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 折扣: -{0}% {1} 的本地化字符串。
        /// </summary>
        internal static string AppDiscount {
            get {
                return ResourceManager.GetString("AppDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - DLC: {0} 的本地化字符串。
        /// </summary>
        internal static string AppDlcInfo {
            get {
                return ResourceManager.GetString("AppDlcInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 游戏本体: {0} {1} 的本地化字符串。
        /// </summary>
        internal static string AppFullGame {
            get {
                return ResourceManager.GetString("AppFullGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 分类: {0} 的本地化字符串。
        /// </summary>
        internal static string AppGenres {
            get {
                return ResourceManager.GetString("AppGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已申请 的本地化字符串。
        /// </summary>
        internal static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Metacritic 评分: {0} 的本地化字符串。
        /// </summary>
        internal static string AppMetacriticScore {
            get {
                return ResourceManager.GetString("AppMetacriticScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 折扣: 未打折 的本地化字符串。
        /// </summary>
        internal static string AppNoDiscount {
            get {
                return ResourceManager.GetString("AppNoDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 发型商: {0} 的本地化字符串。
        /// </summary>
        internal static string AppPublishers {
            get {
                return ResourceManager.GetString("AppPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 发售日期: {0} 的本地化字符串。
        /// </summary>
        internal static string AppReleasedDate {
            get {
                return ResourceManager.GetString("AppReleasedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -  [{0}] 的本地化字符串。
        /// </summary>
        internal static string AppReleasedDateEx {
            get {
                return ResourceManager.GetString("AppReleasedDateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 简介: {0} 的本地化字符串。
        /// </summary>
        internal static string AppShortDescription {
            get {
                return ResourceManager.GetString("AppShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Steam 评价数量: {0} 的本地化字符串。
        /// </summary>
        internal static string AppSteamRecommended {
            get {
                return ResourceManager.GetString("AppSteamRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Sub/{0} {1} 的本地化字符串。
        /// </summary>
        internal static string AppSubInfo {
            get {
                return ResourceManager.GetString("AppSubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 支持平台: Win{0} Mac{1} Linux{2} 的本地化字符串。
        /// </summary>
        internal static string AppSupportedPlatforms {
            get {
                return ResourceManager.GetString("AppSupportedPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 类型: {0} 的本地化字符串。
        /// </summary>
        internal static string AppType {
            get {
                return ResourceManager.GetString("AppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLC 的本地化字符串。
        /// </summary>
        internal static string AppTypeDLC {
            get {
                return ResourceManager.GetString("AppTypeDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 / 软件 的本地化字符串。
        /// </summary>
        internal static string AppTypeGame {
            get {
                return ResourceManager.GetString("AppTypeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        internal static string AppTypeMusic {
            get {
                return ResourceManager.GetString("AppTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} | {1} 的本地化字符串。
        /// </summary>
        internal static string AreaItem {
            get {
                return ResourceManager.GetString("AreaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} | {1} | * 的本地化字符串。
        /// </summary>
        internal static string AreaItemCurrent {
            get {
                return ResourceManager.GetString("AreaItemCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误, {0} 必须为整数 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotInteger {
            get {
                return ResourceManager.GetString("ArgumentNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - ASF版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEAsfVersion {
            get {
                return ResourceManager.GetString("ASFEAsfVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本:  的本地化字符串。
        /// </summary>
        internal static string ASFECurrentVersion {
            get {
                return ResourceManager.GetString("ASFECurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线版本:  的本地化字符串。
        /// </summary>
        internal static string ASFEOnlineVersion {
            get {
                return ResourceManager.GetString("ASFEOnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEPluginVersion {
            get {
                return ResourceManager.GetString("ASFEPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ASFEUPDATE / AU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string ASFEUpdateTips {
            get {
                return ResourceManager.GetString("ASFEUpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ASFEVERSION / AV 检查插件更新 的本地化字符串。
        /// </summary>
        internal static string ASFEVersionTips {
            get {
                return ResourceManager.GetString("ASFEVersionTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 附件:  的本地化字符串。
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 | 区域名称 | 当前区域 的本地化字符串。
        /// </summary>
        internal static string AvailableAreaHeader {
            get {
                return ResourceManager.GetString("AvailableAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应为空 的本地化字符串。
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 类型无效 [SUB|BUNDLE] 的本地化字符串。
        /// </summary>
        internal static string CartInvalidType {
            get {
                return ResourceManager.GetString("CartInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车是空的 的本地化字符串。
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0} {1} {2:F2} 的本地化字符串。
        /// </summary>
        internal static string CartItemInfo {
            get {
                return ResourceManager.GetString("CartItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作为礼物购买: {0} 的本地化字符串。
        /// </summary>
        internal static string CartPurchaseGift {
            get {
                return ResourceManager.GetString("CartPurchaseGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为自己购买: {0} 的本地化字符串。
        /// </summary>
        internal static string CartPurchaseSelf {
            get {
                return ResourceManager.GetString("CartPurchaseSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空购物车: {0} 的本地化字符串。
        /// </summary>
        internal static string CartResetResult {
            get {
                return ResourceManager.GetString("CartResetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车总额: {0:F2} {1} 的本地化字符串。
        /// </summary>
        internal static string CartTotalPrice {
            get {
                return ResourceManager.GetString("CartTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份已经自动清理 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份清理失败 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam商店的Cookies: 的本地化字符串。
        /// </summary>
        internal static string ClientCookies {
            get {
                return ResourceManager.GetString("ClientCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令帮助: 的本地化字符串。
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到相关命令的帮助 的本地化字符串。
        /// </summary>
        internal static string CommandHelpCmdNotFound {
            get {
                return ResourceManager.GetString("CommandHelpCmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0} {1} : {2} 的本地化字符串。
        /// </summary>
        internal static string CommandHelpNoShortName {
            get {
                return ResourceManager.GetString("CommandHelpNoShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无描述 的本地化字符串。
        /// </summary>
        internal static string CommandHelpNoUsage {
            get {
                return ResourceManager.GetString("CommandHelpNoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0} / {1} {2} : {3} 的本地化字符串。
        /// </summary>
        internal static string CommandHelpWithShortName {
            get {
                return ResourceManager.GetString("CommandHelpWithShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string CookieItem {
            get {
                return ResourceManager.GetString("CookieItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 是 NULL 的本地化字符串。
        /// </summary>
        internal static string DataIsNull {
            get {
                return ResourceManager.GetString("DataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 {0} 的评测:  的本地化字符串。
        /// </summary>
        internal static string DeleteReview {
            get {
                return ResourceManager.GetString("DeleteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 描述: {0} 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者特性已开启 的本地化字符串。
        /// </summary>
        internal static string DevFeatureEnabledWarning {
            get {
                return ResourceManager.GetString("DevFeatureEnabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载插件失败! 的本地化字符串。
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领取每日贴纸: {0} 的本地化字符串。
        /// </summary>
        internal static string EventClaimItem {
            get {
                return ResourceManager.GetString("EventClaimItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日探索队列: {0} 的本地化字符串。
        /// </summary>
        internal static string EventQueue {
            get {
                return ResourceManager.GetString("EventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取投票信息失败 的本地化字符串。
        /// </summary>
        internal static string EventReadBadgeStatusFailed {
            get {
                return ResourceManager.GetString("EventReadBadgeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节日活动已完成 的本地化字符串。
        /// </summary>
        internal static string EventTaskComplete {
            get {
                return ResourceManager.GetString("EventTaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Award 投票: {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string EventVoteResponse {
            get {
                return ResourceManager.GetString("EventVoteResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取App信息失败, 可能AppID错误, 或者锁区 的本地化字符串。
        /// </summary>
        internal static string FetchAppDetailFailed {
            get {
                return ResourceManager.GetString("FetchAppDetailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 {0} 失败 的本地化字符串。
        /// </summary>
        internal static string FetchDataFailed {
            get {
                return ResourceManager.GetString("FetchDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 类型无效 [APP|SUB|BUNDLE] 的本地化字符串。
        /// </summary>
        internal static string GameInvalidType {
            get {
                return ResourceManager.GetString("GameInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取在线汇率失败 的本地化字符串。
        /// </summary>
        internal static string GetExchangeRateFailed {
            get {
                return ResourceManager.GetString("GetExchangeRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取个人资料失败 的本地化字符串。
        /// </summary>
        internal static string GetProfileFailed {
            get {
                return ResourceManager.GetString("GetProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取插件发行版信息失败! 的本地化字符串。
        /// </summary>
        internal static string GetReleaseInfoFailed {
            get {
                return ResourceManager.GetString("GetReleaseInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取商店名称出错 的本地化字符串。
        /// </summary>
        internal static string GetStoreNameFailed {
            get {
                return ResourceManager.GetString("GetStoreNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 {0} 发送 的本地化字符串。
        /// </summary>
        internal static string GifteeName {
            get {
                return ResourceManager.GetString("GifteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string GiftMessage {
            get {
                return ResourceManager.GetString("GiftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 {0} 发送 的本地化字符串。
        /// </summary>
        internal static string GiftSignature {
            get {
                return ResourceManager.GetString("GiftSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未加入任何群组 的本地化字符串。
        /// </summary>
        internal static string GroupListEmpty {
            get {
                return ResourceManager.GetString("GroupListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} | {1} | {2} 的本地化字符串。
        /// </summary>
        internal static string GroupListItem {
            get {
                return ResourceManager.GetString("GroupListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No | 群组名称 | 群组ID 的本地化字符串。
        /// </summary>
        internal static string GroupListTitle {
            get {
                return ResourceManager.GetString("GroupListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ ]: 可选参数, &lt; &gt;: 数组(使用,分隔) 的本地化字符串。
        /// </summary>
        internal static string HelpArgsExplain {
            get {
                return ResourceManager.GetString("HelpArgsExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加入 的本地化字符串。
        /// </summary>
        internal static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入群组 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到结果 的本地化字符串。
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出群组: {0} 的本地化字符串。
        /// </summary>
        internal static string LeaveGroup {
            get {
                return ResourceManager.GetString("LeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无参数 的本地化字符串。
        /// </summary>
        internal static string NoArgs {
            get {
                return ResourceManager.GetString("NoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用区域选项, 结算货币为钱包货币 的本地化字符串。
        /// </summary>
        internal static string NoAvailableArea {
            get {
                return ResourceManager.GetString("NoAvailableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML解析失败! 的本地化字符串。
        /// </summary>
        internal static string ParseHtmlFailed {
            get {
                return ResourceManager.GetString("ParseHtmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 Chr_, 联系方式 chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 徽章: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileBadges {
            get {
                return ResourceManager.GetString("ProfileBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好友: {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string ProfileFriends {
            get {
                return ResourceManager.GetString("ProfileFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileGames {
            get {
                return ResourceManager.GetString("ProfileGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileGroups {
            get {
                return ResourceManager.GetString("ProfileGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指南: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileGuide {
            get {
                return ResourceManager.GetString("ProfileGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人资料: 的本地化字符串。
        /// </summary>
        internal static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艺术作品: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileImages {
            get {
                return ResourceManager.GetString("ProfileImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileLevel {
            get {
                return ResourceManager.GetString("ProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileNickname {
            get {
                return ResourceManager.GetString("ProfileNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评测: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileRecommended {
            get {
                return ResourceManager.GetString("ProfileRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileScreenshots {
            get {
                return ResourceManager.GetString("ProfileScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileState {
            get {
                return ResourceManager.GetString("ProfileState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileVideos {
            get {
                return ResourceManager.GetString("ProfileVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创意工坊: {0} 的本地化字符串。
        /// </summary>
        internal static string ProfileWorkshop {
            get {
                return ResourceManager.GetString("ProfileWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 基准汇率 {0} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryAboutBaseRate {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 计算结果由 {0} 生成, 仅供参考 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryAboutPlugin {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 在线汇率数据来自 ExchangeRate-API.com 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryAboutRateSource {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutRateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 汇率数据更新时间: {0:g} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryAboutUpdateTime {
            get {
                return ResourceManager.GetString("PruchaseHistoryAboutUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 额度*1.8 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryCreditMax {
            get {
                return ResourceManager.GetString("PruchaseHistoryCreditMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 额度*1.0 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryCreditMin {
            get {
                return ResourceManager.GetString("PruchaseHistoryCreditMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 外部*1.8 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryExternalMax {
            get {
                return ResourceManager.GetString("PruchaseHistoryExternalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 外部*1.0 - 送礼: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryExternalMin {
            get {
                return ResourceManager.GetString("PruchaseHistoryExternalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据说明: 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryGroupAbout {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 额度推算(仅供参考): 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryGroupGiftCredit {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupGiftCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  2.其他类型的消费: 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryGroupOther {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据统计(仅供参考): 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryGroupStatus {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  1.按购买类型分类(不含已退款的消费): 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryGroupType {
            get {
                return ResourceManager.GetString("PruchaseHistoryGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 外部消费总和: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryStatusTotalExternalPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryStatusTotalExternalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 礼物赠送总和: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryStatusTotalGift {
            get {
                return ResourceManager.GetString("PruchaseHistoryStatusTotalGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 有效额度总和: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryStatusTotalPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryStatusTotalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 外部: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeExternal {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 礼物赠送: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeGiftPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeGiftPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 游戏内购: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeInGamePurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeInGamePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 市场购买: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeMarketPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeMarketPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 市场出售: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeMarketSelling {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeMarketSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 其他类型: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeOther {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 退款: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeRefunded {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 商店购买: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeStorePurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeStorePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 余额: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeWallet {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 余额充值: {0:0.00} {1} 的本地化字符串。
        /// </summary>
        internal static string PruchaseHistoryTypeWalletPurchase {
            get {
                return ResourceManager.GetString("PruchaseHistoryTypeWalletPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车是空的,无需结账 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartFailureEmpty {
            get {
                return ResourceManager.GetString("PurchaseCartFailureEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, FinalizeTransaction 返回值为空 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartFailureFinalizeTransactionIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartFailureFinalizeTransactionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, GetFinalPrice 返回值为空 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartGetFinalPriceIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartGetFinalPriceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, transID 为Null 的本地化字符串。
        /// </summary>
        internal static string PurchaseCartTransIDIsNull {
            get {
                return ResourceManager.GetString("PurchaseCartTransIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买完成, 消费金额: {0} 的本地化字符串。
        /// </summary>
        internal static string PurchaseDone {
            get {
                return ResourceManager.GetString("PurchaseDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败, 余额未变动 的本地化字符串。
        /// </summary>
        internal static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商店消费记录统计: 的本地化字符串。
        /// </summary>
        internal static string PurchaseHistorySummary {
            get {
                return ResourceManager.GetString("PurchaseHistorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评测发布失败: {0} 的本地化字符串。
        /// </summary>
        internal static string RecommendPublishFailed {
            get {
                return ResourceManager.GetString("RecommendPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评测发布成功 的本地化字符串。
        /// </summary>
        internal static string RecommendPublishSuccess {
            get {
                return ResourceManager.GetString("RecommendPublishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该查询未传回任何结果 的本地化字符串。
        /// </summary>
        internal static string SearchResultEmpty {
            get {
                return ResourceManager.GetString("SearchResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppID | 名称 的本地化字符串。
        /// </summary>
        internal static string SearchResultTitle {
            get {
                return ResourceManager.GetString("SearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算货币设置: {0} 的本地化字符串。
        /// </summary>
        internal static string SetCurrentCountry {
            get {
                return ResourceManager.GetString("SetCurrentCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} == NULL 的本地化字符串。
        /// </summary>
        internal static string SomethingIsNull {
            get {
                return ResourceManager.GetString("SomethingIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   - {0}/{1} {2} {3:F2} {4} 的本地化字符串。
        /// </summary>
        internal static string StoreItem {
            get {
                return ResourceManager.GetString("StoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string StoreItemHeader {
            get {
                return ResourceManager.GetString("StoreItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到商店页 的本地化字符串。
        /// </summary>
        internal static string StorePageNotFound {
            get {
                return ResourceManager.GetString("StorePageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 链接: {0} 的本地化字符串。
        /// </summary>
        internal static string SubLink {
            get {
                return ResourceManager.GetString("SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 尺寸: {0:0.000} KB 的本地化字符串。
        /// </summary>
        internal static string SubSize {
            get {
                return ResourceManager.GetString("SubSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未加入 的本地化字符串。
        /// </summary>
        internal static string Unjoined {
            get {
                return ResourceManager.GetString("Unjoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新失败, 压缩包内容解析失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFiledWithZip {
            get {
                return ResourceManager.GetString("UpdateFiledWithZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新完成, 重启ASF即可应用, 如果不兼容请更新ASF版本 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以使用命令 ASFEUPDATE / AU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string UpdateTips {
            get {
                return ResourceManager.GetString("UpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 版本: {0} 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱包区域未知 的本地化字符串。
        /// </summary>
        internal static string WalletAreaUnknown {
            get {
                return ResourceManager.GetString("WalletAreaUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
